parameters:

- name: training_data_source
  displayName: Azure Storage Container name containing training data
  default: ""
- name: model_destination
  displayName: Azure Storage Container name that will contain the model
  default: ""
- name: storage_account_name
  displayName: Storage account name
  default: ""
- name: training_data_sas_token
  displayName: SAS Token for training data storage container
  default: ""
- name: model_sas_token
  displayName: SAS Token for models storage container
  default: ""

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'mkdir python/ml/training-data'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure for Students Starter(26e343c1-e278-49f7-9847-4afa8c7a4ced)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage blob download-batch --destination python/ml/training-data --pattern "*" --source "${{ parameters.training_data_source }}" --account-name "${{ parameters.storage_account_name }}" --sas-token "${{ parameters.training_data_sas_token }}"'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'
    addToPath: true
    architecture: 'x64'

- script: |
    python -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
    python python/ml/train_script.py
  displayName: 'Training'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure for Students Starter(26e343c1-e278-49f7-9847-4afa8c7a4ced)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage blob upload --account-name ${{ parameters.storage_account_name }} --container-name "${{ parameters.model_destination }}" --name "model.joblib" --file "outputs/model.joblib" --sas-token "${{ parameters.model_sas_token }}"'
