trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.12.2'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Azure for Students Starter(26e343c1-e278-49f7-9847-4afa8c7a4ced)'
    backendAzureRmResourceGroupName: 'rg-terraform-backend'
    backendAzureRmStorageAccountName: 'stesgitbackend1'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: '-auto-approve'
    environmentServiceNameAzureRM: 'Azure for Students Starter(26e343c1-e278-49f7-9847-4afa8c7a4ced)'
