trigger:
  branches:
    include: [ main ]

pool:
  vmImage: 'ubuntu-latest'

variables:
  ACR_NAME: cvdregistry
  IMAGE_NAME: cvd-backend

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'

- script: |
    python -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    source venv/bin/activate
    pytest tests
  displayName: 'Run unit tests'

- task: Docker@2
  inputs:
    containerRegistry: '$(ACR_NAME)'
    repository: '$(IMAGE_NAME)'
    command: 'buildAndPush'
    Dockerfile: Dockerfile
    tags: |
      $(Build.BuildId)
