trigger:
- none

parameters:
  - name: mysql_user
    displayName: MySQL username
    type: string
    default: ""

  - name: mysql_password
    displayName: MySQL password
    type: string
    default: ""

  - name: mysql_dbname
    displayName: MySQL database name
    type: string
    default: ""

  - name: mysql_server_name
    displayName: MySQL server name
    type: string
    default: ""

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.12.2'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Azure for Students Starter(26e343c1-e278-49f7-9847-4afa8c7a4ced)'
    backendAzureRmResourceGroupName: 'rg-terraform-backend'
    backendAzureRmStorageAccountName: 'stesgitbackend1'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: '-var="mysql_user=${{ parameters.mysql_user}}" -var="mysql_password=${{ parameters.mysql_password }}" -var="mysql_dbname=${{ parameters.mysql_dbname }}" -var="mysql_server_name=${{ parameters.mysql_server_name }}" -auto-approve'
    environmentServiceNameAzureRM: 'Azure for Students Starter(26e343c1-e278-49f7-9847-4afa8c7a4ced)'
