parameters:
- name: models_sas_token
  displayName: SAS Token for models storage container
  default: ""

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: Bash@3  
  inputs:
    targetType: 'inline'
    script: 'az storage blob download --container-name models --name model.joblib --file python/backend/model.joblib --account-name stgthe3neurons --sas-token "${{ parameters.models_sas_token }}"'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'zip -r python/backend/app.zip python/backend'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'az webapp deploy --resource-group rgthe3neurons --name app-CKpJKaLE --src-path app.zip --sas-token "${{ parameters.models_sas_token }}'

